# LEA

## API functions

In [1]:
import requests
from datetime import datetime
import pandas as pd

In [2]:
# TfL API credentials
app_id = '721e2c10e8334c5c8c12f53b7fe2f986'
app_key = 'd82918317ac047c7af9c5eaebaad456f'

## TfL API base URL
base_url = 'https://api.tfl.gov.uk/'

## max 500 Requests per min!!

In [4]:
## Arrival time function for StopPoint
def get_arrival_times(stop_id):
    url = f"https://api.tfl.gov.uk/StopPoint/{stop_id}/Arrivals?app_id={app_id}&app_key={app_key}"
    print('loading:',url)
    response = requests.get(url)
    if response.status_code == 200:
        return response.json()
    else:
        return None

## StopPoint IDs for Holborn Station and nearby bus stops
holborn_station_id = '940GZZLUHBN'
bus_stop_ids = [
    '490000091A',
    '490000091B'
]

## Arrival times for Holborn Station
holborn_arrivals = get_arrival_times(holborn_station_id)

## Arrival times for bus stations
bus_stop_arrivals = [];
for bus_stop_id in bus_stop_ids:
    bus_stop_arrivals.append(get_arrival_times(bus_stop_id))

loading: https://api.tfl.gov.uk/StopPoint/940GZZLUHBN/Arrivals?app_id=721e2c10e8334c5c8c12f53b7fe2f986&app_key=d82918317ac047c7af9c5eaebaad456f
loading: https://api.tfl.gov.uk/StopPoint/490000091A/Arrivals?app_id=721e2c10e8334c5c8c12f53b7fe2f986&app_key=d82918317ac047c7af9c5eaebaad456f
loading: https://api.tfl.gov.uk/StopPoint/490000091B/Arrivals?app_id=721e2c10e8334c5c8c12f53b7fe2f986&app_key=d82918317ac047c7af9c5eaebaad456f

## Build time table and countdown:

In [17]:
timetable = [];

# build timetable for Holborn Underground Station:
for elem in holborn_arrivals:
    stationName = elem['stationName'];
    expectedArrival = elem['expectedArrival'];
    expectedArrival_dt = datetime.strptime(elem['expectedArrival'], '%Y-%m-%dT%H:%M:%SZ');
    expectedArrival_minutes = (datetime.now() - expectedArrival_dt).seconds/60
    destinationName = elem['destinationName'];
    direction = elem['direction'];
    # arrival soon?
    if direction=='inbound': 
        timetable.append([stationName,destinationName,expectedArrival,expectedArrival_minutes]);

# build timetable for bus stations:
#for bus_stop_arrival in bus_stop_arrivals:
    # parse in the same way than u station above and add elements to timetable

[None, None]

## Output Screen

In [22]:
# Use pandas dataframe:
timetable_pd = pd.DataFrame(timetable, columns=['stationName','destinationName','expectedArrival','expectedArrival_minutes'])
timetable_pd = timetable_pd.sort_values('expectedArrival_minutes')
timetable_pd

,stationName,destinationName,expectedArrival,expectedArrival_minutes
7,Holborn Underground Station,Ealing Broadway Underground Station,2024-06-20T17:34:17Z,1417.600000
17,Holborn Underground Station,Heathrow Terminal 5 Underground Station,2024-06-20T17:33:18Z,1418.583333
4,Holborn Underground Station,West Ruislip Underground Station,2024-06-20T17:33:17Z,1418.600000
0,Holborn Underground Station,North Acton Underground Station,2024-06-20T17:30:17Z,1421.600000
14,Holborn Underground Station,Rayners Lane Underground Station,2024-06-20T17:29:18Z,1422.583333
1,Holborn Underground Station,Northolt Underground Station,2024-06-20T17:27:17Z,1424.600000
8,Holborn Underground Station,White City Underground Station,2024-06-20T17:27:17Z,1424.600000
12,Holborn Underground Station,Heathrow Terminal 4 Underground Station,2024-06-20T17:25:18Z,1426.583333
6,Holborn Underground Station,Ealing Broadway Underground Station,2024-06-20T17:24:17Z,1427.600000
11,Holborn Underground Station,Heathrow Terminal 5 Underground Station,2024-06-20T17:23:18Z,1428.583333
18,Holborn Underground Station,Heathrow Terminal 4 Underground Station,2024-06-20T17:21:18Z,1430.583333
13,Holborn Underground Station,Uxbridge Underground Station,2024-06-20T17:20:18Z,1431.583333
10,Holborn Underground Station,Heathrow Terminal 4 Underground Station,2024-06-20T17:18:18Z,1433.583333
3,Holborn Underground Station,West Ruislip Underground Station,2024-06-20T17:16:17Z,1435.600000
9,Holborn Underground Station,Rayners Lane Underground Station,2024-06-20T17:15:18Z,1436.583333
16,Holborn Underground Station,Heathrow Terminal 5 Underground Station,2024-06-20T17:14:18Z,1437.583333
5,Holborn Underground Station,Ealing Broadway Underground Station,2024-06-20T17:13:17Z,1438.600000
15,Holborn Underground Station,Uxbridge Underground Station,2024-06-20T17:12:48Z,1439.083333
2,Holborn Underground Station,West Ruislip Underground Station,2024-06-20T17:12:17Z,1439.600000